version: '3.9'

services:
  postgres:
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=crm
    volumes:
      - PGDATA:/var/lib/postgresql/data

volumes:
  PGDATA:
