version: '3.9'

services:
  postgres:
    image: postgres:16.2
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - PGDATA:/var/lib/postgresql/data
  node:
    build:
      dockerfile: Dockerfile.node
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ./server/src:/app/src

volumes:
  PGDATA:
